default_install_hook_types: [pre-commit, pre-push]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: detect-private-key
    -   id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
    -   id: no-commit-to-branch
        args: ["--branch", "main"]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format

-   repo: https://github.com/ricky-lim/pre-commit-hooks
    rev: v0.5.0
    hooks:
    -   id: check-changelog
        stages: [pre-push]
